### ISSUE TITLE
Can't convert object of type 'numpy.ndarray' to 'str' for 'filename'

### ISSUE THREAD

**Issue by lhumke** [ShivamChourey/Harris-Corner-Detection#1]
In line 90 should be just the string of the filename

**Comment by AnupKumarGupta** [comment]
Change `firstimagename = cv2.imread("YourFileName.png")`  at [line 90](https://github.com/ShivamChourey/Harris-Corner-Detection/blob/master/Corner_Detection.py#L90) to `firstimagename = "YourFileName.png"`.

**Comment by sym330** [comment]
firstimage = cv2.imread("imgname.jpg", cv2.IMREAD_GRAYSCALE)

**Comment by lhumke** [comment]
I already fixed it and created a Pull Request #2 it just needs to be accepted
